const nationalMockNotices = [
  {
    id: 'eum-mock-001',
    source: 'eum-mock',
    sourceLabel: '토지이음 Mock',
    type: '주민공람',
    title: '부산 해운대구 우동 도시관리계획(도로) 결정(변경)(안) 주민공람',
    period: '2026.03.18. ~ 2026.04.01.',
    sido: '부산광역시',
    sigungu: '해운대구',
    regionLabel: '부산광역시 해운대구',
    department: '해운대구 도시계획과',
    place: '해운대구청 도시계획과',
    link: 'https://www.eum.go.kr/',
    excerpt: '서울 외 지역은 토지이음 수집 로직 부재 시 목업 데이터로 대체되며, 동일 카드 구조로 렌더링됩니다.',
    isMock: true,
    updatedAt: '2026-03-20T00:00:00Z',
  },
  {
    id: 'eum-mock-002',
    source: 'eum-mock',
    sourceLabel: '토지이음 Mock',
    type: '인터넷 의견청취',
    title: '경기도 성남시 분당구 지구단위계획 결정(안) 인터넷 의견청취',
    period: '2026.03.16. ~ 2026.03.30.',
    sido: '경기도',
    sigungu: '성남시 분당구',
    regionLabel: '경기도 성남시 분당구',
    department: '성남시 도시계획과',
    place: '토지이음 의견청취 게시판',
    link: 'https://www.eum.go.kr/web/ar/lu/luLandDet.jsp',
    excerpt: '백엔드 수집기 도입 전까지는 지역 선택 흐름이 끊기지 않도록 대표 공고를 목업으로 제공합니다.',
    isMock: true,
    updatedAt: '2026-03-20T00:00:00Z',
  },
  {
    id: 'eum-mock-003',
    source: 'eum-mock',
    sourceLabel: '토지이음 Mock',
    type: '주민공람',
    title: '대전광역시 유성구 개발제한구역 관리계획 변경(안) 공람',
    period: '2026.03.11. ~ 2026.03.26.',
    sido: '대전광역시',
    sigungu: '유성구',
    regionLabel: '대전광역시 유성구',
    department: '유성구 도시재생과',
    place: '유성구청 민원실',
    link: 'https://www.eum.go.kr/',
    excerpt: '토지이음 실데이터를 대체하는 전국 목업 데이터입니다.',
    isMock: true,
    updatedAt: '2026-03-20T00:00:00Z',
  },
  {
    id: 'eum-mock-004',
    source: 'eum-mock',
    sourceLabel: '토지이음 Mock',
    type: '인터넷 의견청취',
    title: '제주특별자치도 제주시 도시관리계획(공원) 결정(변경)(안) 의견청취',
    period: '2026.03.08. ~ 2026.03.24.',
    sido: '제주특별자치도',
    sigungu: '제주시',
    regionLabel: '제주특별자치도 제주시',
    department: '제주시 도시계획과',
    place: '토지이음 인터넷 의견청취',
    link: 'https://www.eum.go.kr/',
    excerpt: '실서비스 전환 시 이 영역은 EUM 크롤러 결과로 대체됩니다.',
    isMock: true,
    updatedAt: '2026-03-20T00:00:00Z',
  },
];

export function getNationalMockNotices() {
  return nationalMockNotices;
}
